name: Destroy Kubernetes Namespace on Closed Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.number }}
      NAMESPACE: preview-${{ github.event.number }}
      KUBECONFIG_PATH: /home/runner/.kube/config

    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG_PATH

      - name: Checkout infra repo
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.DOCKER_USERNAME }}/${{ vars.INFRA_REPO_NAME }}
          path: infra
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Install helmfile
        run: |
          wget -O helmfile.tar.gz https://github.com/helmfile/helmfile/releases/download/v1.1.2/helmfile_1.1.2_linux_amd64.tar.gz
          tar -xzf helmfile.tar.gz
          sudo mv helmfile /usr/local/bin/
          helmfile --version

      - name: Init helmfile
        run: |
          cd infra/stuffcontrol
          helmfile init --force

      - name: Deploy infrastructure on first deploy
        run: |
          cd infra/stuffcontrol
          helmfile -e preview \
            --state-values-set namespace=$NAMESPACE,number=$PR_NUMBER destroy

      - name: Delete Kubernetes Namespace
        run: |
          kubectl delete namespace $NAMESPACE || echo "Namespace $NAMESPACE does not exist"