name: Destroy Kubernetes Namespace on Closed Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: preview-${{ github.event.pull_request.head.ref }}
      KUBECONFIG_PATH: /home/runner/.kube/config

    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG_PATH

      - name: Delete Kubernetes Namespace
        run: |
          kubectl delete namespace $NAMESPACE || echo "Namespace $NAMESPACE does not exist"